openapi: 3.0.4
info:
  title: Image Caption
  description: >-
    Image Caption is an AI-powered tool that generates descriptive captions for
    images. Simply upload an image and receive a natural language description of
    its contents.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/imagecaption:
    post:
      summary: Caption Image
      description: >-
        Image Caption is an AI-powered tool that generates descriptive captions
        for images. Simply upload an image and receive a natural language
        description of its contents.
      operationId: imagecaption
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  caption: >-
                    A golden retriever running through a grassy field on a sunny
                    day
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: 'File to upload (accepted: .jpg, .jpeg, .png, .gif, max 5MB)'
                  acceptedTypes:
                    - .jpg
                    - .jpeg
                    - .png
                    - .gif
                  maxSizeMB: 5
              required:
                - image
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
sampleRequest:
  image: >-
    https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/640px-Cat03.jpg
