name: apiverve_imagecaption
description: Image Caption is an AI-powered tool that generates descriptive captions for images. Simply upload an image and receive a natural language description of its contents.
version: 1.1.14
homepage: https://apiverve.com/marketplace/imagecaption?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/imagecaption-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
